import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Bismarckschule',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="de">
      <head>
        <title>test</title>
        <style>
          @import “navbar.css”;
        </style>
      </head>
      <body className={inter.className}>{children}
        <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"></link>
          <nav id="navbar" className="">
            <div className="nav-wrapper">
              <div className="logo">
                <a href="#home"><i className="fa fa-angellist"></i> Logo</a>
              </div>

              <ul id="menu">
                <li><a href="#home">Home</a></li>
                <li><a href="#services">Services</a></li>
                <li><a href="#about">About</a></li>
                <li><a href="#contact">Contact</a></li>
              </ul>
            </div>
          </nav>


          <div className="menuIcon">
            <span className="icon icon-bars"></span>
            <span className="icon icon-bars overlay"></span>
          </div>


          <div className="overlay-menu">
            <ul id="menu">
              <li><a href="#home">Home</a></li>
              <li><a href="#services">Services</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
          </div>

          <script src="navbar.js"></script>
      </body>
    </html>
  )
}
